teamcity-agent:
  build: ./image
  container_name: "${TEAMCITY_AGENT_NAME}"
  environment:
    - "TEAMCITY_AGENT_NAME=${TEAMCITY_AGENT_NAME}"
    - "TEAMCITY_SERVER_URL=${TEAMCITY_SERVER_URL}"
  privileged: true
  restart: always
  volumes:
    - "${TEAMCITY_AGENT_DIR}:/data"
