proxy:
  build: ../proxy
  container_name: proxy
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - "${NGINX_CERTS}:/etc/nginx/certs"
    - "/var/run/docker.sock:/tmp/docker.sock:ro"

db:
  container_name: db
  environment:
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  image: mariadb:latest

web:
  build: .
  container_name: web
  environment:
    VIRTUAL_HOST: alpha.build.nativecode.com
    WORDPRESS_DB_CREATOR_USER: "${WORDPRESS_DB_CREATOR_USER}"
    WORDPRESS_DB_CREATOR_PASSWORD: "${WORDPRESS_DB_CREATOR_PASSWORD}"
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
    WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
  links:
    - db
